services:
  server:
    build:
      context: server
      dockerfile: ../Dockerfile
    command: ["bash", "-c", "npm install && npm start"]
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    depends_on:
      database:
        condition: service_healthy
    environment:
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${SERVER_PORT}
      DATABASE_URL: mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database/${DATABASE_NAME}
  
  client:
    build:
      context: client
      dockerfile: ../Dockerfile
    command: ["bash", "-c", "npm install && npm run dev"]
    ports:
      - 5173:5173
    volumes:
      - type: bind
        source: ./client
        target: /usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
  
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    ports:
      - "3630:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55